#!/usr/bin/env bash
#Creating script that loops 1-20, bad luck from China after 4, bad luck from Japan after 9, and bad luck from Italy after 17
i=0
while [ $i -ge 23 ]
do
case "$i" in
4)
echo "bad luck from China"
;;
9)
echo "bad luck from Japan"
;;
17)
echo "bad luck from Italy"
;;
esac
echo {1..20}
((i++))
done
