#!/usr/bin/env bash
#Creating script that loops 1-20, bad luck from China after 4, bad luck from Japan after 9, and bad luck from Italy after 17
i=1
while [ $i -le 20 ]
do
case "$i" in
5)
echo "bad luck from China"
;;
10)
echo "bad luck from Japan"
;;
18)
echo "bad luck from Italy"
;;
esac
echo "$i"
((i++))
done
