#!/usr/bin/env bash
#Displaying time for 12 hours and 59 minutes
hours=0
while [ $hours -lt 13 ]; do
echo "Hour: $hours"
((hours++))
minutes=1
while [ $minutes -lt 60 ]; do
echo "$minutes"
((minutes++))
done
done
