#!/usr/bin/env bash
#Displaying information about the school file with if and else
if [ -e "./school" ]; then 
echo "school file exists"
else
echo "school file does not exist"
fi
if [ -s "./school" ]; then
	echo "school file is not empty"
else
	echo "school file is empty"
fi
if [ -f "./school" ]; then
	echo "school is a regular file"
fi
